* Update config file to include decomposition patterns for control and   adjoint modifiers, along with exp_pauli and multi-control gates * Add separate tests suite for testing against real server * Extend integration tests to run one C++ and one Python test * Docs fixes
Signed-off-by: Pradnya Khalate <pkhalate@nvidia.com>

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -268,7 +268,7 @@ jobs:
                 filelist="targettests/quantinuum/*.cpp targettests/quantinuum_ng/*.cpp docs/sphinx/targets/python/quantinuum.py"
                 ;;
               tii)
-                filelist="targettests/tii/*.cpp"
+                filelist="docs/sphinx/targets/cpp/tii.cpp docs/sphinx/targets/python/tii.py"
                 ;;
             esac
             echo "testlist=$filelist" >> $GITHUB_OUTPUT
@@ -408,7 +408,9 @@ jobs:
             tii)
               echo "### Setting up TII account" >> $GITHUB_STEP_SUMMARY
               echo "::add-mask::${{ secrets.TII_AUTH_TOKEN }}"
+              echo "::add-mask::${{ secrets.TII_PROJECT }}"
               echo "TII_AUTH_TOKEN=${{ secrets.TII_AUTH_TOKEN }}" >> $GITHUB_ENV
+              echo "TII_PROJECT=${{ secrets.TII_PROJECT }}" >> $GITHUB_ENV
               ;;
           esac
         shell: bash
@@ -696,10 +698,24 @@ jobs:
                 ;;
 
               tii)
-                nvq++ -v $filename --target tii
-                test_status=$?
-                if [ $test_status -eq 0 ]; then
-                  ./a.out
+                if [[ "$filename" == *.cpp ]]; then
+                  nvq++ -v $filename --target tii --tii-device tii-sim --tii-project ${{ secrets.TII_PROJECT }}
+                  test_status=$?
+                  if [ $test_status -eq 0 ]; then
+                    ./a.out
+                    test_status=$?
+                    if [ $test_status -eq 0 ]; then
+                      echo ":white_check_mark: Successfully ran test: $filename" >> $GITHUB_STEP_SUMMARY
+                    else
+                      echo ":x: Test failed (failed to execute): $filename" >> $GITHUB_STEP_SUMMARY
+                      test_err_sum=$((test_err_sum+1))
+                    fi
+                  else
+                    echo ":x: Test failed (failed to compile): $filename" >> $GITHUB_STEP_SUMMARY
+                    test_err_sum=$((test_err_sum+1))
+                  fi
+                elif [[ "$filename" == *.py ]]; then
+                  python3 $filename 1> /dev/null
                   test_status=$?
                   if [ $test_status -eq 0 ]; then
                     echo ":white_check_mark: Successfully ran test: $filename" >> $GITHUB_STEP_SUMMARY
@@ -708,9 +724,9 @@ jobs:
                     test_err_sum=$((test_err_sum+1))
                   fi
                 else
-                  echo ":x: Test failed (failed to compile): $filename" >> $GITHUB_STEP_SUMMARY
-                  test_err_sum=$((test_err_sum+1))
-                fi
+                  echo "::warning::Unsupported file type: $filename"
+                  echo ":warning: Test skipped (unsupported file type): $filename" >> $GITHUB_STEP_SUMMARY
+                  test_skip_sum=$((test_skip_sum+1))
                 ;;
             esac
           done
